package com.example.common

import org.apache.spark.sql.types.StructType
object Schemas {
  val schema1 = new StructType().add("FIPStxt","String")
    .add("State","String")
    .add("Area_name","String")
    .add("Rural-urban_Continuum_Code_2003","String")
    .add("Urban_Influence_Code_2003","String")
    .add("Rural-urban_Continuum_Code_2013","String")
    .add("Urban_Influence_Code_2013","String")
    .add("POVALL_2018","String")
    .add("CI90LBAll_2018","String")
    .add("CI90UBALL_2018","String")
    .add("PCTPOVALL_2018","String")
    .add("CI90LBALLP_2018","String")
    .add("CI90UBALLP_2018","String")
    .add("POV017_2018","String")
    .add("CI90LB017_2018","String")
    .add("CI90UB017_2018","String")
    .add("PCTPOV017_2018","String")
    .add("CI90LB017P_2018","String")
    .add("CI90UB017P_2018","String")
    .add("POV517_2018","String")
    .add("CI90LB517_2018","String")
    .add("CI90UB517_2018","String")
    .add("PCTPOV517_2018","String")
    .add("CI90LB517P_2018","String")
    .add("CI90UB517P_2018","String")
    .add("MEDHHINC_2018","String")
    .add("CI90LBINC_2018","String")
    .add("CI90UBINC_2018","String")
    .add("POV04_2018","String")
    .add("CI90LB04_2018","String")
    .add("CI90UB04_2018","String")
    .add("PCTPOV04_2018","String")
    .add("CI90LB04P_2018","String")
    .add("CI90UB04P_2018","String")

  val schema2 = new StructType().add("Sensor","String")
    .add("Mnemonic","String")
    .add("data","Int")
    .add("timestamp","String")

  val schemaUS = new StructType().add("year","String")
    .add("harvestUS","String")
    .add("YieldUS","String")
    .add("ProductionUS","String")

  val schemaROW = new StructType().add("year","String")
    .add("harvestROW","String")
    .add("YieldROW","String")
    .add("ProductionROW","String")

  case class aadhardtl(aua: String, sa: String,  res_state: String)
  case class poverty(State : String, Area_name : String,  Urban_Influence_Code_2003: String, Rural_urban_Continuum_Code_2013 :String,PCTPOVALL_2018 :String,PCTPOV017_2018:String)
  case class statesinfo(State_ab : String, State_name : String)
  case class BarleyUS(year:String,harvestUS:String,YieldUS:String,ProductionUS:String)
  case class BarleyROW(year:String,harvestROW:String,YieldROW:String,ProductionROW:String)

}
